name: environment_test
on: workflow_dispatch
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.7
    steps:
    - name: Hello World
      run: |-
        echo 'Hello World!'
        echo 'This is the delivery pipeline'
  I-Have-Code:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.7
    needs:
    - Hello-World
    steps:
    - uses: actions/checkout@v2
    - name: Code Has Arrived
      run: |-
        ls -al
        echo '^^^That should look familiar^^^'
  Run-With-Node:
    runs-on: ubuntu-latest
    container:
      image: node:17.2
    needs:
    - Hello-World
    steps:
    - name: Running In A Container With Node
      run: node -v
  Hold-For-Approval:
    environment:
      name: approval
    runs-on: ubuntu-latest
    needs:
    - Run-With-Node
    - I-Have-Code
    steps:
    - run: echo 'approved'
  Now-Complete:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.7
    needs:
    - Hold-For-Approval
    steps:
    - name: Approval Complete
      run: echo 'Do work once the approval has completed'
