name: valet-dev-testing/circle-demo/Example_Workflow
on:
  push:
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.7
    steps:
    - name: Hello World
      run: |-
        echo 'Hello World!'
        echo 'This is the delivery pipeline'
  I-Have-Code:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.7
    needs:
    - Hello-World
    steps:
    - uses: actions/checkout@v2
    - name: Code Has Arrived
      run: |-
        ls -al
        echo '^^^That should look familiar^^^'
  Run-With-Node:
    runs-on: ubuntu-latest
    container:
      image: node:17.2
    needs:
    - Hello-World
    steps:
    - name: Running In A Container With Node
      run: node -v
  Hold-For-Approval:
    environment:
      name: staging
    runs-on: ubuntu-latest
    needs:
    - Run-With-Node
    - I-Have-Code
  Now-Complete:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.7
    needs:
    - Hold-For-Approval
    steps:
    - name: Approval Complete
      run: echo 'Do work once the approval has completed'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
